language: csharp

env:
  global:
   # Encrypted COVERITY_SCAN_TOKEN
   - secure: "YrWIFcVaJC64ud9b+kIiK8y9wROSfTzo6zvTVFwPrb/tS7QfIufOQNfADg8uAMx++ME1CASHpu+7xVNf6wFcFj7uTh0bheZzRVk9RVTXaK5K/O8/fqvmoRMCVvyGnhcsrOOZ2M88EY5JHCJXEvIQUHJQUkL/Qi/KkE2owHAJp1Y="

install:
  - nuget restore MegaApiClient.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild MegaApiClient.sln /p:Configuration='Release'
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MegaApiClient.Tests/bin/Release/MegaApiClient.Tests.dll
  - nuget pack MegaApiClient.nuspec

addons:
  coverity_scan:
    project:
      name: "gpailler/MegaApiClient"
      description: "Build submitted via Travis CI"
    notification_email: gregoire@pailler.fr
    build_command_prepend: "xbuild MegaApiClient.sln /t:Clean"
    build_command:   "xbuild MegaApiClient.sln /t:Rebuild /p:Platform='Any CPU';Configuration='Coverity'"
    branch_pattern: coverity_scan