version: 1.1.0.{build}
skip_tags: true
configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore "MegaApiClient.sln"
build:
  project: MegaApiClient.sln
  verbosity: minimal
after_build:
  - nuget pack "MegaApiClient.nuspec"

test:
  assemblies: '**\*.Tests.dll'

artifacts:
  - path: '**\*.nupkg'
    name: Nuget